apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: apps
  name: demo-teis
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: app.motoren.site
    http:
      paths:
      - path: /demoteis
        pathType: Prefix
        backend:
          service:
            name: demo-teis
            port:
              number: 80