apiVersion: v1
kind: Service
metadata:
  name: demo-teis
  namespace: apps
spec:
  selector:
    app: demo-teis
  ports:
  - name: demo-teis
    protocol: TCP
    port: 80
    targetPort: http-web-svc